name: CI - pytest (Allure + HTML)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Chrome / Chromium (ensure browser + driver available)
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (pytest) with Allure results and pytest-html
        env:
          PYTHONPATH: .
        run: |
          mkdir -p reports/allure-results
          mkdir -p reports/screenshots
          pytest --alluredir=reports/allure-results --html=reports/report.html --self-contained-html -q

      # Upload artifacts even if tests fail
      - name: Upload pytest-html report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report
          path: reports/report.html

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: reports/allure-results

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: reports/screenshots
